ALTER TABLE POINTS_KEY_CONFIG ADD COLUMN IF NOT EXISTS PERIOD_UNIT VARCHAR(16);
ALTER TABLE POINTS_KEY_CONFIG ADD COLUMN IF NOT EXISTS PERIOD_COUNT INT DEFAULT 0;
UPDATE POINTS_KEY_CONFIG SET PERIOD_UNIT = 'DAY', PERIOD_COUNT = SUBSCRIBE_DURATION_DAYS WHERE PERIOD_UNIT IS NULL AND SUBSCRIBE_DURATION_DAYS IS NOT NULL;
ALTER TABLE POINTS_KEY_CONFIG DROP COLUMN IF EXISTS SUBSCRIBE_DURATION_DAYS;
ALTER TABLE POINTS_KEY_CONFIG DROP COLUMN IF EXISTS VALID_FROM;

ALTER TABLE USER_POINTS DROP COLUMN IF EXISTS SUBSCRIBE_DURATION_DAYS;
ALTER TABLE USER_POINTS DROP COLUMN IF EXISTS SUBSCRIBE_STATUS;
